### ISSUE TITLE
Question - Plans for next v9

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-next.js#101]
Hello !

What is you plan about :
- Dynamic Routing 
- API Routes
- Automatic Static Optimization

These are great improvements in the next environment ! I don't know what is your vision @danielcondemarin on this and how this plugin should handle theses features/improvements.

Thanks.

**Comment by danielcondemarin** [comment]
Hello! Sorry, been very busy lately but definitely Next 9 support will be coming. 

Find the Dynamic Routing Proposal here:  https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/105. 

API Routes and Automatic Static Optimisation is also really cool stuff I'll be creating some proposals for over the next few weeks 👍

**Comment by Vadorequest** [comment]
Is Next v9 compatible with the current version of this plugin? Even if all features aren't supported yet.

**Comment by danielcondemarin** [comment]
> Is Next v9 compatible with the current version of this plugin? Even if all features aren't supported yet.

It's probably not compatible, although I haven't tried it. 
This plugin relies on next's build output which has changed. For example, built pages being outputted as html when they don't use `getInitialProps` (aka Automatic Static Optimisation).

**Comment by aygee** [comment]
Not compatible. I just tried it :)

**Comment by danielcondemarin** [comment]
Raised another RFC for automatic static optimisation, https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/107

**Comment by aygee** [comment]
> Not compatible. I just tried it :)

UPDATE: I should clarify that I managed to get this working Next v9 without much effort. I got an error earlier but it was due to misconfiguration on my part. 

I haven't got dynamic routing in my project - I don't think it will work out of the box as discussed in this thread.

**Comment by jishaal** [comment]
@aygee How did you get it working?

I get the following error

```
Serverless plugin "serverless-nextjs-plugin" initialization errored: Cannot read property 'serverless-nextjs' of undefined
```

**Comment by aygee** [comment]
@jishaal I also had that error before but managed to get rid of it eventually after trying few different things, but I don't know what fixed it. What is your version of serverless? Mine is 1.41.1. Did you use yarn or npm? (I used yarn) maybe try to delete node_modules folder and do another `yarn install`

**Comment by jishaal** [comment]
Adding the below to `serverless.yml` fixed it, using `1.48.2`

```yml
custom:
  serverless-nextjs: {}
```

Manages to push the stack out to AWS now, but having issues when hitting the endpoints, I am guessing because it cannot handle the static html files with Automatic Static Optimization? I need to investigate further, would love to somehow get it working!

**Comment by aygee** [comment]
@jishaal good point, I think it's expecting that key in the `serverless.yml`

For static files, they need to be hosted somewhere else, because aws lambda won't be able to serve the static files. You can follow the instruction how to host the static files in s3: https://github.com/danielcondemarin/serverless-nextjs-plugin#hosting-static-assets

**Comment by jishaal** [comment]
> For static files, they need to be hosted somewhere else

Hmm I got this and I believe this is working fine for things like images/script etc for me ie. bucket gets created and these files end up there. What I think the issue is that due to Automatic Static Optimization, if a route does not have `getInitialProps`, it gets prerendered as a HTML file. This _is_ a static asset but what I don't understand is how do I get this to the static asset bucket and have the lambda return this? 

>If getInitialProps is absent, Next.js will statically optimize your page automatically by prerendering it to static HTML.

https://github.com/zeit/next.js/#automatic-prerendering

Currently the lambda  gets uploaded the html file and a weird related js file and its all falls apart

```js
// index.html
  const page = require("./index.html.original.js");
  const handlerFactory = require("next-aws-lambda");

  module.exports.render = (event, context, callback) => {
    const handler = handlerFactory(page);
    handler(event, context, callback);
  };
```
and the file it references

```
// index.html.original.js, has the static html in this
<!DOCTYPE html><html><head><title>....
```

**Comment by jishaal** [comment]
FYI I got around this by adding a noop `getInitialProps` to each of my pages so stop automatic-prerendering. Hacky but works for now

**Comment by mattdell** [comment]
I missed this thread, but raised one for API Routes over at #116

**Comment by johhansantana** [comment]
@mattdell what version of next@8 does it support api routes? I'm trying to upload latest `"next": "8.1.1-canary.70"` but I am getting a `"message": "Internal server error"` when I try to access the index page. This happens with next@9 as well but I have some api endpoints that I need to use.

**Comment by aygee** [comment]
@johhansantana Have you checked your server log?

**Comment by johhansantana** [comment]
@aygee I think it's this error `Cannot find module './sls-next-build/index.js` not sure how to fix this though :(

**Comment by mattdell** [comment]
@johansantana read through #116 as I had the exact same problem

You need

* Next 9.0.4
* AWS Lambda on version 10

**Comment by johhansantana** [comment]
Got it! The only problem now are the assets aren't being loaded because of the url stage suffix. I guess this is fixed when you put your custom domain?

**Comment by danielcondemarin** [comment]
I have recently released https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-component which targets `nextjs 9.0` and has full feature parity. Please check it out. 
In terms of the next-plugin I believe next 9 support is nearly there but might take some time before is fully complete.
