### ISSUE TITLE
Same domain format as other @serverless components

### ISSUE THREAD

**Issue by RodrigoEspinosa** [danielcondemarin/serverless-next.js#163]
I would like to suggest using the same `domain` format as the other components from @serverless-components. 

I'll be happy to create a Pull Request if you think that's alright.

**Comment by danielcondemarin** [comment]
Thanks for bringing to my attention @RodrigoEspinosa. For now I prefer to keep it as is, my worry with having a `string` for the domain like the [website component does](https://github.com/serverless-components/website#3-configure) is that it doesn't work for dotted subdomains, i.e. 
domain: `foo.bar.example.com`. You can't determine where the subdomain ends / domain starts. That's why I went with a clear separation of the two.

**Comment by RodrigoEspinosa** [comment]
That's a valid point. However, I feel like that could be coded as well, the domain would be right after the tld (right-to-left). Meaning, if splitting by dots, the domain is `array[-2].array[-1]` (pseudocode) -- no?

**Comment by RodrigoEspinosa** [comment]
Alternatively, another option is to check the type for the input. If it's an array follow the current behavior. If it's a string, goes through the splitting.
