### ISSUE TITLE
Support "build once" paradigm

### ISSUE THREAD

**Issue by skycremaschinin** [danielcondemarin/serverless-next.js#179]
Hi, 
i'm not sure if this could be an issue related to this component or serverless framework, but could be a natural continuation  of this brand new feature:

[How to support multiple environments ](https://github.com/danielcondemarin/serverless-next.js/issues/177)

I'd like to implement "build once" paradigm, splitting the build phase and deploy phase, in order to manage a flow such as:

- build app ( _.next_ assets creation )

- deploy app to stage (staging _.serverless_ assets creation and deploy of _.next_ assets on staging aws account)

- deploy app to prod (production _.serverless_ assets creation and deploy of _.next_ assets on production aws account)

could be a good idea? 
@danielcondemarin what do you think about?

**Comment by danielcondemarin** [comment]
@skycremaschinin I think this is a great idea! Decoupling the build from deployment could be useful in many cases. 

It could be a new input to the component, i.e.

```yml
myApp
  component: serverless-next.js
  inputs:
   build: false
```

This way the component can simply assume the app has been built and uses the `.next` directory in `nextConfigDir`. It should be a straightforward change to make as well. 

Would this work for what you have in mind?

I'm more than happy to take contributions on this 🙏 Otherwise I'll look into it as soon as I get a chance 🙂

**Comment by skycremaschinin** [comment]
@danielcondemarin yes, your solution seems the quicker and safer.
But i suppose that the `.serverless_nextjs`folder too should be considered an app's artifact and not re-built. it ins't?
i'm glad to contribute, i'll work on it in the next few days (nights) 😉

**Comment by danielcondemarin** [comment]
@skycremaschinin That's a good point, `.serverless-next.js` shouldn't be rebuilt either 👍

**Comment by danielcondemarin** [comment]
Closing, this is now deployed on @1.4.0 🎉
