### ISSUE TITLE
Support for catch all routes

### ISSUE THREAD

**Issue by tiotdev** [danielcondemarin/serverless-next.js#286]
**Is your feature request related to a problem? Please describe.**
Next.js supports catch all routes routing (https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes). This is not supported yet, instead I receive a 404.

**Describe the solution you'd like**
Support for catch all dynamic routes

**Comment by Linux249** [comment]
Also just run in this issue - here is a detailed description of the new next.js-feature: https://nextjs.org/blog/next-9-2#catch-all-dynamic-routes

**Comment by danielcondemarin** [comment]
Hi folks, just published @1.9.1 with support for this 🙌

**Comment by paleite** [comment]
Looks really great, but I can't seem to get it to work for API-routes: https://nextjs.org/docs/api-routes/dynamic-api-routes#catch-all-api-routes 

My file is `pages/api/[...path].js` locally, but it's missing in the API-lambda. Other API-paths still work though.

**Comment by danielcondemarin** [comment]
> Looks really great, but I can't seem to get it to work for API-routes: https://nextjs.org/docs/api-routes/dynamic-api-routes#catch-all-api-routes
> 
> My file is `pages/api/[...path].js` locally, but it's missing in the API-lambda. Other API-paths still work though.

There seems to be a problem with file names like `[...whatever]` not getting uploaded to AWS Lambda. I can definitely see the built file by the component, e.g. `.serverless_nextjs/api-lambda/[...path].js` but for reasons unknown to me it doesn't get uploaded to the Lambda. Maybe is an issue in https://github.com/serverless-components/aws-lambda/ which is actually what handles the zipping of the artifact and uploading but I had a look there and couldn't find anything obvious. 
The reason why it worked last night for me it was because I was testing using a statically optimised catch all route which works fine as is just an HTML file uploaded to S3.

**Comment by paleite** [comment]
@danielcondemarin Thank you so much! I appreciate that 😊

Let me know if I can help somehow? I have no experience with serverless, but maybe I can help anyways?

Without any insight into the inner workings of the `aws-lambda`-component, I would guess that there's some path resolution algorithm that's trying to resolve the path and failing at that. E.g. trying to resolve `/api/[...path].js` by doing something like `/api/[` + `..` + `.path].js` and then erroring out because path `/api/[` doesn't exist.

What do you think?

**Comment by paleite** [comment]
Thanks to your hint I found the cause of the issue. I created a PR for it with the aws-lambda-crew: https://github.com/serverless-components/aws-lambda/pull/26

**Comment by ration** [comment]
I also was hit by this. Using the latest version of `globby` in aws-lambda will also fix this.

**Comment by patricktyndall** [comment]
So what's the recommended approach here? I have an SSR'd `pages/blog/[...all].js` file that is giving me cloudfront 503s.

**Comment by danielcondemarin** [comment]
I am pleased to announce I've just released `serverless-next.js@1.11.1` which completes this work 🎉
