### ISSUE TITLE
Are components DOA? — plugin/component feature parity

### ISSUE THREAD

**Issue by mikestopcontinues** [danielcondemarin/serverless-next.js#317]
Progress on Serverless Components seems to have ground to a halt, and being able to deploy a modern Next project to AWS requires multiple serverless.yml, because we can only get Next@9 with components, but easy access to the rest of AWS with old-style serverless. Does it really make sense to push everyone toward components when the Serverless team seems ambivalent about the issue?

**Comment by barrysteyn** [comment]
@mikestopcontinues I agree. Actually, the Serverless team really seems to have dropped the ball on this one: They have pushed for components, get everyone excited, and then changed their mind. My own two cents is that this is a tragedy because the components were easy to use and well designed. However, I believe that @danielcondemarin is in the process of moving things to cdk, which is supported by Amazon and will be a good path forward.

**Comment by mikestopcontinues** [comment]
Thanks @barrysteyn . That's good to hear, as I just experimenting with cdk. Once I get deploy working, I'm gonna experiment with localstack to fill in the local dev gap. If you try cdk, beware the docs. I've crossed a bunch of non-functional examples, and exports moved to different packages.

**Comment by danielcondemarin** [comment]
I'm closing this as Serverless components have now announced General Availability - https://serverless.com/blog/serverless-components-ga/. There will be work that needs doing in this component to support the new components "cloud approach" but will be doing that as part of an RFC separately.
