### ISSUE TITLE
404 Error Page not working

### ISSUE THREAD

**Issue by sidarthar** [danielcondemarin/serverless-next.js#378]
**Describe the bug**
When using `next@9.3.5`, navigating to an invalid URL does not show the 404 error page. Instead, you see 200 | An unexpected error has occurred.

**To Reproduce**
1. Clone this repository: [https://github.com/sidarthar/serverless-nextjs-404-error](https://github.com/sidarthar/serverless-nextjs-404-error)
2. Run `npx serverless` to deploy 
3. After deployed, visit the appUrl/pageThatDoesNotExist

**Expected behavior**
Should see a 404 | Page Not Found error.

**Screenshots**
![image](https://user-images.githubusercontent.com/12951761/80873633-fcebb200-8c87-11ea-9167-10b4e58a811c.png)

**Desktop (please complete the following information):**
 - OS: N/A
 - Version next@9.3.5, serverless-next.js@1.11.0

**Additional context**
When using `next@9.3.4`, the 404 page works as expected.

**Comment by danielcondemarin** [comment]
Thanks for reporting! I suspect this started happening since the introduction of https://nextjs.org/docs/advanced-features/custom-error-page#404-page. If that's the case, this would need to be supported in serverless-next.js, probably changing [this](https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/lambda-at-edge/src/default-handler.ts#L41).
If someone can confirm and is happy to PR I'll happily accept contrib. 👍

**Comment by bhall2001** [comment]
This may be related...
https://github.com/zeit/next.js/issues/12199

**Comment by sidarthar** [comment]
I believe that the issue is because of [https://github.com/zeit/next.js/pull/11561/files](https://github.com/zeit/next.js/pull/11561/files)

On line 283 of next-serverless-loader.ts, 

``${page === '/_error' ? `res.statusCode = 404` : ''}`` was deleted and replaced with
 
``
${
          page === '/_error'
            ? `
          if (!res.statusCode) {
            res.statusCode = 404
          }
        `
            : ''
}
``

If I understand correctly, `res.statusCode = 200` is set before rendering the error page, so it doesn't reach the line to set `res.statusCode = 404`.

**Comment by danielcondemarin** [comment]
> I believe that the issue is because of [#11561](https://github.com/zeit/next.js/pull/11561)
> 
> On line 283 of next-serverless-loader.ts,
> 
> `` ${page === '/_error' ? `res.statusCode = 404` : ''} `` was deleted and replaced with
> 
> `` ${ page === '/_error' ? ` if (!res.statusCode) { res.statusCode = 404 } ` : '' } ``
> 
> If I understand correctly, `res.statusCode = 200` is set before rendering the error page, so it doesn't reach the line to set `res.statusCode = 404`.

Good catch. 
Maybe setting `status` and `statusDescription` as `undefined` [here](https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/lambda-at-edge-compat/next-aws-cloudfront.js#L84) is the fix. 
I think it should be fine but would need some testing to ensure it doesn't break some use case.

**Comment by marcin-piela** [comment]
Is there any workaround (to implement in app) without waiting for new package version?

**Comment by lone-cloud** [comment]
So I quite literally did what @danielcondemarin suggested in his previous comment and the 404 status is now being returned correctly. I have not noticed any regressions with the change. However, it is still being rendering in the _error template instead of the 404 one. I assume this has never worked for this project before and will require work.

Commit here: https://github.com/lone-cloud/serverless-next.js/commit/834886a41324500a5c29831d3614366b08725c5f

You can test by forking my set_status_undefined/378 branch locally, run `npm install && npm run packages-install` on it and change your component in serverless.yml to point to its local path like `component: '../serverless-next.js/packages/serverless-component'`.
