### ISSUE TITLE
TypeError: req.logIn is not a function - Passport.js

### ISSUE THREAD

**Issue by mertyildiran** [danielcondemarin/serverless-next.js#384]
First of all, this error is quite similar to https://github.com/jaredhanson/passport/issues/436 but it only happens on AWS Lambda@Edge so I guess it's more relevant to `serverless-nextjs` or [serverless](https://github.com/serverless/serverless) in general.

**Describe the bug**
The error log from CloudWatch:
```json
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: req.logIn is not a function",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "req.logIn is not a function",
        "stack": [
            "TypeError: req.logIn is not a function",
            "    at Strategy.strategy.success (/var/task/pages/api/auth.js:46906:13)",
            "    at verified (/var/task/pages/api/auth.js:28897:10)",
            "    at Strategy.module.exports.ELJM.passport__WEBPACK_IMPORTED_MODULE_0___default.a.use.passport_local__WEBPACK_IMPORTED_MODULE_2__.Strategy [as _verify] (/var/task/pages/api/auth.js:13978:105)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: req.logIn is not a function",
        "    at process.on (/var/runtime/index.js:37:15)",
        "    at process.emit (events.js:198:13)",
        "    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)",
        "    at process._tickCallback (internal/process/next_tick.js:69:34)"
    ]
}
```
The line it points out to:
```javascript
        req.logIn(user, options, function(err) {
```

**To Reproduce**
1. Clone: https://github.com/hoangvvo/nextjs-mongodb-app
2. Deploy it using `serverless` and `serverless-next.js`
3. Try to signup or login
4. Chrome Developer Tools > Network, you will see the `503` response

**Expected behavior**
Everything works fine on my local machine, so the error should not occur on AWS Lambda@Edge.

**Information about dependencies:**
 - `next@9.3.4`
 - `serverless-next.js@1.11.1`
 - `passport@^0.4.1`
 - `express@^4.17.1`
 - `serverless --version`:
```
Framework Core: 1.69.0
Plugin: 3.6.9
SDK: 2.3.0
Components: 2.30.5
```

**Comment by danielcondemarin** [comment]
Thanks for reporting! And the great write up.

I believe the issue lies in the compat layer https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/lambda-at-edge-compat. 

More specifically the [artificial request object](https://github.com/danielcondemarin/serverless-next.js/blob/47fb657f49ba68cd79a8b8b4328c797bda9e7d24/packages/lambda-at-edge-compat/next-aws-cloudfront.js#L92) it creates, needs to inherit the Prototype chain of `http.IncomingMessage` which passportjs is monkey patching. That will then give access to custom methods libraries like passport add to nodejs request. 

I’m happy to take contrib on this otherwise will take a look as soon as I can 🙂

**Comment by mertyildiran** [comment]
@danielcondemarin OK, probably I'm going to deep copy `cfRequest` to `req` with the purpose of preserving the functions and attributes instead of creating a blank request object on [this line](https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/lambda-at-edge-compat/next-aws-cloudfront.js#L92).

I'm going to give you an update or open a PR as soon as I'm done this.

**Comment by danielcondemarin** [comment]
@mertyildiran I'm afraid the Contributing guide needs updating. The steps there are for the older version of this project using the [serverless plugin ](https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-plugin) which deploys to API Gateway and Lambda. What you want is the newer version of the project deploys to CloudFront and Lambda@Edge which lives [here](https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-component). 

I'll get the contributing guide updated today! On the meantime you could do the following to test your changes locally:

```
# your serverless.yml
nextApp:
  component: "/path/to/your/copy/serverless-next.js/packages/serverless-component"
  inputs:
    ...
```

The `component` field needs to point at the parent directory of a serverless.js file. 

One more thing, I don't think copying cfRequest will work. That is because cfRequest is not of type http.IncomingMessage. `cfRequest` is simply an object that AWS is passing to Lambda@Edge. 

A working solution would be something along the lines of:

```
const req = Object.create(http.IncomingMessage.prototype); // this should copy over things like logIn and logOut
```

request is also an instance of `Stream.Readable` so the above probably won't be exactly it.
