### ISSUE TITLE
serverless offline

### ISSUE THREAD

**Issue by justinwhall** [danielcondemarin/serverless-next.js#93]
Just updated to `2.0.6-alpha.0`. I like the simplicity of the new config and compat/custom lambda. It appears now running serverless offline is broken? All assets locally 404? Am I missing something in the config. I'm _not_ using an assetPrefix while checking sls offline. With no assetPrevix running sls offline should load local lambdas in the `.next` directory no?

**Comment by danielcondemarin** [comment]
@justinwhall local assets are not hosted or served locally by the plugin, therefore doesn't work with `serverless-offline`. Tbh I'm debating whether to spend too much time on fully supporting a local setup or not. 
My current plan is to achieve feature parity with nextjs so you can just run `next dev`. Of course there might be issues specific to serverless which would be nice to check before deploying, but this should be the exception rather than the rule.  

Having said that serverless-offline supports `resourceRoutes` which is the same the plugin uses on deployment: https://github.com/dherault/serverless-offline#http-proxy. I think it would be worth investigating this, as it might solve this problem with little effort.

**Comment by Elyx0** [comment]
I'm currently looking at using
```
plugins:
  - serverless-offline # this plugin uses offline hooks
  - serverless-s3-sync # not required but this plugin uses the s3Sync custom config
  - serverless-s3-local # creates the local 'bucket'
  - serverless-s3-local-sync # specify this plugin last, as it relies on the others
 ```
But just the fact that it needs 3 plugins + a conf just to support this case is kind of annoying...
Plus it doesn't solve the need of mapping `.next` vs `_next`

**Comment by RichiCoder1** [comment]
@danielcondemarin If you're interesting, I may make a PR for this. This should be accomplishable by adding special static and public handlers that act as local proxies to those files when running locally, yes?

**Comment by RichiCoder1** [comment]
Added a rough PR here: https://github.com/danielcondemarin/serverless-nextjs-plugin/pull/120
Uses my idea of just setting up ad-hoc handlers when the offline plugin is present.

**Comment by danielcondemarin** [comment]
Closing this as local dev won't be supported going forwards, that will be left to next.js dev tooling
